name: Generate Packages

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  create-release:
    permissions: write-all
    name: Generate Release
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.generate-packages.outputs.upload_url }}
    steps:
      - name: Generate Packages
        id: generate-packages
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: 'false'
          prerelease: 'false'
  build-desktop:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    needs: create-release
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.create-release.outputs.tag_name }}
          repository: '${{ github.repository }}'

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Change wrapper permissions
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew packageDistributionForCurrentOS

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-package
          path: build/compose/binaries

  release-desktop:
    permissions: write-all
    needs: build-desktop
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows package
        uses: actions/download-artifact@v4
        with:
          name: windows-latest-package
          path: ./main/msi

      - name: Download Linux package
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-package
          path: ./main/deb

      - name: Download macOS package
        uses: actions/download-artifact@v4
        with:
          name: macos-latest-package
          path: ./main/dmg

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./main/msi
          asset_name: devutils-${{github.ref_name}}.msi
          asset_content_type: application/x-msi

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./main/deb
          asset_name: devutils-${{github.ref_name}}.deb
          asset_content_type: application/x-deb

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./main/dmg
          asset_name: devutils-${{github.ref_name}}.dmg
          asset_content_type: application/x-apple-diskimage